baseURL = "https://www.yourdomain.com"
languageCode = "en-us"
title = "Trilink Collaborative"

# Hugo configuration
enableRobotsTXT = true
enableEmoji = true
disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[related]
  includeNewer = true
  threshold = 80
  toLower = false
  [[related.indices]]
    name = "keywords"
    weight = 100
  [[related.indices]]
    name = "date"
    weight = 10