# Streamlined Main Navigation - matches existing content
[[main]]
name = "Home"
url = "/"
weight = 10

[[main]]
name = "Services"
url = "/#services"
weight = 20
hasChildren = true

  [[main]]
  name = "Bookkeeping & Accounting"
  url = "/services/bookkeeping/"
  parent = "Services"
  weight = 21
  hasChildren = true

    [[main]]
    name = "Service Overview"
    url = "/services/bookkeeping-overview/"
    parent = "Bookkeeping & Accounting"
    weight = 210

    [[main]]
    name = "Account Setup"
    url = "/services/account-setup-consulting/"
    parent = "Bookkeeping & Accounting"
    weight = 211

    [[main]]
    name = "Account Cleanup"
    url = "/services/account-cleanup-catch-up/"
    parent = "Bookkeeping & Accounting"
    weight = 212

    [[main]]
    name = "Monthly Maintenance"
    url = "/services/ongoing-bookkeeping-monthly-close/"
    parent = "Bookkeeping & Accounting"
    weight = 213

    [[main]]
    name = "Year-End Close"
    url = "/services/year-end-adjustments/"
    parent = "Bookkeeping & Accounting"
    weight = 214

    [[main]]
    name = "Payroll Setup & Management"
    url = "/services/payroll-setup-processing/"
    parent = "Bookkeeping & Accounting"
    weight = 215

    [[main]]
    name = "Training & Support"
    url = "/services/software-training/"
    parent = "Bookkeeping & Accounting"
    weight = 216

  [[main]]
  name = "Business Process Automation"
  url = "/services/business-process-automation/"
  parent = "Services"
  weight = 22

  [[main]]
  name = "Operations & Growth Strategy"
  url = "/services/operations-growth-strategy/"
  parent = "Services"
  weight = 23

[[main]]
name = "Pricing"
url = "/pricing/"
weight = 30

[[main]]
name = "About"
url = "/about/"
weight = 40

[[main]]
name = "Contact"
url = "/contact/"
weight = 50

# Footer menu sections
[[footer]]
name = "Privacy Policy"
url = "/legal/privacy/"
weight = 10

[[footer]]
name = "Terms of Service"
url = "/legal/terms/"
weight = 20

# Footer Quick Access menu
[[footer_quick]]
name = "About"
url = "/about/"
weight = 10

[[footer_quick]]
name = "Pricing"  
url = "/pricing/"
weight = 20

[[footer_quick]]
name = "Contact"
url = "/contact/"
weight = 30

[[footer_quick]]
name = "Blog"
url = "/blog/"
weight = 40

# Footer Resources menu
[[footer_resources]]
name = "Case Studies"
url = "/resources/case-studies/"
weight = 10

[[footer_resources]]
name = "Downloads"
url = "/resources/downloads/"
weight = 20

[[footer_resources]]
name = "Webinars"
url = "/resources/webinars/"
weight = 30